export const terms = {
  listen: "listening",
  silent: "stopped",
  otherHost: "non-local URL",
  otherPort: "different port",
  stale: "types not rebuilt",
  unfetched: "types not updated",
  invalidUrl: "URL error",
  answers: "reachable",
  noAnswer: "unreachable",
  requestTimeout: "request timed out",
  requestNetworkError: "network error",
  requestHttpError: "HTTP error",
  matches: "matches",
  start: "Start",
  rebuild: "Rebuild types",
  refetch: "Fetch @mf-types",
  refetchPending: "waiting for types download",
  typesUnknown: "types freshness unknown",
  typesDisabled: "type consumption disabled",
  refetchFailed: "types download failed",
  refresh: "Refresh",
  discover: "Find microfrontends",
  urlMissing: "URL is missing",
  urlMalformed: "URL is invalid",
  empty: "No Module Federation configs found",
  scriptMissing: "script not found",
  exposes: "exposes",
  shared: "shared",
  singleton: "singleton",
  folder: "folder",
  localPort: "local port",
  manifest: "manifest",
  manifestOff: "disabled in config",
  url: "URL",
  portInUrl: "URL port",
  link: "connection",
  externalManifest: "external manifest",
  types: "types",
  zip: "zip",
  noWorkspace: "not in workspace",
} as const;
